# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

tcovCpp <- function(x, beta) {
    .Call(`_ICSClust_tcovCpp`, x, beta)
}

scovCpp <- function(x, m, beta) {
    .Call(`_ICSClust_scovCpp`, x, m, beta)
}

